import type { LivingLesson } from "../engine/types";

export const davidExperience: LivingLesson = {
  id: "bible-david-living-demo",
  moduleId: "bible-david",
  title: "The Road to Goliath",
  summary: "A cinematic demonstration of timeline direction, discovery, reflection, memory and contextual recommendations.",
  estimatedMinutes: 6,
  learningObjectives: ["Recognize how courage is prepared before crisis", "Observe before explanation", "Connect courage to leadership"],
  access: { tier: "explorer", previewAllowed: true },
  scenes: [
    {
      id: "shepherd-field",
      kind: "story",
      eyebrow: "Years before the battlefield",
      title: "A shepherd learns to stand alone",
      displayText: "Long before anyone called him a hero, David was responsible for lives more vulnerable than his own.",
      narration: "Courage did not suddenly appear when David saw Goliath. It was trained here, in the quiet fields, when nobody was applauding.",
      durationMs: 9000,
      camera: "wide",
      transition: "dissolve",
      background: { id: "field", gradient: "linear-gradient(135deg,#3f6212,#0f172a)", alt: "A quiet shepherd field at dusk" },
      actors: [],
      overlays: [{ id: "idea", kind: "key-takeaway", title: "Watch closely", body: "Preparation often happens before opportunity appears.", position: "top-right" }],
      timeline: [
        { id: "p0", atMs: 0, type: "set-phase", payload: { phase: "preload" } },
        { id: "b0", atMs: 100, type: "show-background" },
        { id: "p1", atMs: 500, type: "set-phase", payload: { phase: "story" } },
        { id: "n0", atMs: 1200, type: "start-narration" },
        { id: "o0", atMs: 2600, type: "show-overlay", targetId: "idea" },
        { id: "m0", atMs: 8200, type: "memory-hook", targetId: "quiet-courage" },
        { id: "done", atMs: 9000, type: "complete-scene" },
      ],
      memoryHooks: [{ id: "quiet-courage", topic: "Courage is trained in private", importance: "high", conceptIds: ["courage", "preparation"] }],
    },
    {
      id: "army-discovery",
      kind: "discovery",
      eyebrow: "Discovery moment",
      title: "An army that will not move",
      displayText: "Thousands are armed. One voice has stopped them all.",
      narration: "Before I explain what happened, study the scene. What seems to be controlling the army: Goliath's strength, or their fear?",
      durationMs: 10500,
      camera: "tracking",
      transition: "fade",
      background: { id: "battlefield", gradient: "linear-gradient(135deg,#78350f,#111827 62%)", alt: "A dusty battlefield" },
      interaction: {
        id: "observe-army",
        mode: "discovery",
        prompt: "What do you notice about the soldiers before David arrives?",
        choices: [
          { id: "unprepared", label: "They have no weapons" },
          { id: "fear", label: "Fear has made their strength useless" },
          { id: "small", label: "The army is too small" },
          { id: "lost", label: "They do not know where Goliath is" },
        ],
        hint: "Look at the difference between having power and using it.",
        pauseTimeline: true,
      },
      timeline: [
        { id: "db", atMs: 0, type: "show-background" },
        { id: "dp", atMs: 400, type: "set-phase", payload: { phase: "discovery" } },
        { id: "dn", atMs: 1500, type: "start-narration" },
        { id: "di", atMs: 5200, type: "show-interaction" },
        { id: "dm", atMs: 9800, type: "memory-hook", targetId: "fear-freezes" },
        { id: "dd", atMs: 10500, type: "complete-scene" },
      ],
      memoryHooks: [{ id: "fear-freezes", topic: "Fear can neutralize existing ability", importance: "high", conceptIds: ["fear", "leadership"] }],
    },
    {
      id: "reflection-courage",
      kind: "reflection",
      eyebrow: "Memory moment",
      title: "Which giant are you waiting to feel ready for?",
      narration: "David did not wait for fear to disappear. He acted from what he had already learned. Take a moment and name one challenge where preparation matters more than confidence.",
      durationMs: 9000,
      camera: "reflection",
      transition: "light",
      background: { id: "reflection", gradient: "linear-gradient(135deg,#1e1b4b,#0f172a)", alt: "A calm reflective space" },
      interaction: {
        id: "personal-reflection",
        mode: "reflection",
        prompt: "Where in your own life could quiet preparation build courage?",
        hint: "Think about school, work, family, faith or a skill you want to master.",
        pauseTimeline: true,
      },
      timeline: [
        { id: "rb", atMs: 0, type: "show-background" },
        { id: "rp", atMs: 250, type: "set-phase", payload: { phase: "reflection" } },
        { id: "rn", atMs: 900, type: "start-narration" },
        { id: "ri", atMs: 4300, type: "show-interaction" },
        { id: "rr", atMs: 8300, type: "recommendation-hook", targetId: "leaders-courage" },
        { id: "rd", atMs: 9000, type: "complete-scene" },
      ],
      recommendationHooks: [{
        id: "leaders-courage",
        trigger: "scene_completed",
        reason: "This learner engaged with courage and leadership through David's story.",
        academyId: "biography",
        moduleId: "great-leaders",
        priority: 80,
      }],
    },
  ],
};
