import type { LivingScene } from "../../engine/types";
import type { StoryJourney } from "../../story/types";

const bg = (id: string, gradient: string, alt: string) => ({ id, gradient, alt });
const completeTimeline = (prefix: string, durationMs: number, phase: string, interaction = false) => [
  { id: `${prefix}-bg`, atMs: 0, type: "show-background" as const },
  { id: `${prefix}-phase`, atMs: 250, type: "set-phase" as const, payload: { phase } },
  { id: `${prefix}-narration`, atMs: 900, type: "start-narration" as const },
  ...(interaction ? [{ id: `${prefix}-interaction`, atMs: Math.max(1800, durationMs - 4500), type: "show-interaction" as const }] : []),
  { id: `${prefix}-complete`, atMs: durationMs, type: "complete-scene" as const },
];

const scenes: LivingScene[] = [
  {
    id: "bethlehem-morning", kind: "story", title: "A family in Bethlehem",
    eyebrow: "Chapter 1 \u00b7 The House of Jesse",
    narration: "Before crowns, battles and songs, there was a household in Bethlehem. Jesse had sons whom others could easily imagine as leaders. David was the one still outside.", displayText: "Before crowns, battles and songs, there was a household in Bethlehem. Jesse had sons whom others could easily imagine as leaders. David was the one still outside.",
    durationMs: 18000, camera: "wide", transition: "dissolve",
    background: bg("bethlehem-morning-bg", "linear-gradient(135deg,#7c5e3c,#14213d)", "A family in Bethlehem \u2014 cinematic illustrated scene"),
    timeline: completeTimeline("bethlehem-morning", 18000, "story", false),
  },
  {
    id: "brothers-line", kind: "discovery", title: "The obvious candidates",
    eyebrow: "Chapter 1 \u00b7 The House of Jesse",
    narration: "Look at the brothers standing before Samuel. Strength is visible. Confidence is visible. But character is harder to see.", displayText: "Look at the brothers standing before Samuel. Strength is visible. Confidence is visible. But character is harder to see.",
    durationMs: 22000, camera: "medium", transition: "dissolve",
    background: bg("brothers-line-bg", "linear-gradient(135deg,#475569,#111827)", "The obvious candidates \u2014 cinematic illustrated scene"),
    interaction: {
      id: "brothers-line-interaction", mode: "discovery", prompt: "What might people notice first when choosing a leader?", pauseTimeline: true, skippable: false,
      choices: [{ id: "brothers-line-0", label: "Appearance and confidence" }, { id: "brothers-line-1", label: "Private character" }, { id: "brothers-line-2", label: "Future decisions" }],
      hint: "Look for the deeper principle, not only the visible action.",
      themes: [
        { id: "appearance", label: "Appearance", keywords: ["appearance", "confidence", "strong"], acknowledgement: "Yes—visible strength and confidence are often what people notice first.", followUp: "What important qualities might remain hidden?" },
        { id: "character", label: "Character", keywords: ["character", "heart", "integrity"], acknowledgement: "You looked beneath the surface. Character is slower to notice, but it shapes every decision.", followUp: "How could someone recognise character before a crisis?" },
      ],
      fallbackResponse: "That is worth noticing. The story is about to challenge the way people recognise leadership.",
    },
    cinematic: { cameraBeats: [{ atMs: 4200, camera: "close" }, { atMs: 12500, camera: "medium" }], silenceWindows: [{ startMs: 7600, endMs: 9000 }] },
    timeline: completeTimeline("brothers-line", 22000, "discovery", true),
  },
  {
    id: "missing-son", kind: "conversation", title: "Someone is missing",
    eyebrow: "Chapter 1 \u00b7 The House of Jesse",
    narration: "Samuel asks a simple question: Are these all your sons? The answer reveals how easily overlooked people can disappear from the room.", displayText: "Samuel asks a simple question: Are these all your sons? The answer reveals how easily overlooked people can disappear from the room.",
    durationMs: 22000, camera: "medium", transition: "dissolve",
    background: bg("missing-son-bg", "linear-gradient(135deg,#365314,#0f172a)", "Someone is missing \u2014 cinematic illustrated scene"),
    interaction: {
      id: "missing-son-interaction", mode: "choice", prompt: "Why do you think David was not invited at first?", pauseTimeline: true, skippable: false,
      choices: [{ id: "missing-son-0", label: "He was considered too young or unimportant" }, { id: "missing-son-1", label: "He had left Bethlehem" }, { id: "missing-son-2", label: "Samuel already knew him" }],
      hint: "Look for the deeper principle, not only the visible action.",
    },
    timeline: completeTimeline("missing-son", 22000, "story", true),
  },
  {
    id: "sheep-at-dusk", kind: "story", title: "Responsibility without applause",
    eyebrow: "Chapter 2 \u00b7 Life in the Fields",
    narration: "David cared for sheep when no audience was watching. Small lives depended on his attention.", displayText: "David cared for sheep when no audience was watching. Small lives depended on his attention.",
    durationMs: 18000, camera: "wide", transition: "dissolve",
    background: bg("sheep-at-dusk-bg", "linear-gradient(135deg,#78350f,#111827)", "Responsibility without applause \u2014 cinematic illustrated scene"),
    overlays: [{ id: "sheep-at-dusk-takeaway", kind: "key-takeaway", title: "Remember", body: "Preparation often begins where nobody is applauding.", position: "bottom-right" }],
    timeline: completeTimeline("sheep-at-dusk", 18000, "story", false),
    memoryHooks: [{ id: "sheep-at-dusk-memory", topic: "Responsibility without applause", importance: "high", conceptIds: ["preparation", "responsibility"] }],
  },
  {
    id: "notice-field", kind: "discovery", title: "What does a shepherd notice?",
    eyebrow: "Chapter 2 \u00b7 Life in the Fields",
    narration: "A shepherd learns to watch weather, distance, danger and the movement of the flock. Attention becomes a form of protection.", displayText: "A shepherd learns to watch weather, distance, danger and the movement of the flock. Attention becomes a form of protection.",
    durationMs: 22000, camera: "medium", transition: "dissolve",
    background: bg("notice-field-bg", "linear-gradient(135deg,#312e81,#0f172a)", "What does a shepherd notice? \u2014 cinematic illustrated scene"),
    interaction: {
      id: "notice-field-interaction", mode: "discovery", prompt: "What skill is David practising here?", pauseTimeline: true, skippable: false,
      choices: [{ id: "notice-field-0", label: "Careful observation" }, { id: "notice-field-1", label: "Public speaking" }, { id: "notice-field-2", label: "Military command" }],
      hint: "Look for the deeper principle, not only the visible action.",
    },
    timeline: completeTimeline("notice-field", 22000, "discovery", true),
  },
  {
    id: "quiet-reflection", kind: "reflection", title: "The work nobody sees",
    eyebrow: "Chapter 2 \u00b7 Life in the Fields",
    narration: "Many important abilities are built quietly. Think about one skill you are developing before anyone notices the result.", displayText: "Many important abilities are built quietly. Think about one skill you are developing before anyone notices the result.",
    durationMs: 22000, camera: "reflection", transition: "dissolve",
    background: bg("quiet-reflection-bg", "linear-gradient(135deg,#7c5e3c,#14213d)", "The work nobody sees \u2014 cinematic illustrated scene"),
    interaction: {
      id: "quiet-reflection-interaction", mode: "reflection", prompt: "What are you preparing for in private?", pauseTimeline: true, skippable: false,
      hint: "Look for the deeper principle, not only the visible action.",
    },
    timeline: completeTimeline("quiet-reflection", 22000, "reflection", true),
  },
  {
    id: "samuel-enters", kind: "story", title: "A prophet arrives",
    eyebrow: "Chapter 3 \u00b7 Samuel Comes to Bethlehem",
    narration: "Samuel comes to Bethlehem carrying both authority and uncertainty. He knows the mission, but not yet the person.", displayText: "Samuel comes to Bethlehem carrying both authority and uncertainty. He knows the mission, but not yet the person.",
    durationMs: 18000, camera: "wide", transition: "dissolve",
    background: bg("samuel-enters-bg", "linear-gradient(135deg,#475569,#111827)", "A prophet arrives \u2014 cinematic illustrated scene"),
    timeline: completeTimeline("samuel-enters", 18000, "story", false),
  },
  {
    id: "eliab-reveal", kind: "discovery", title: "Surely this is the one",
    eyebrow: "Chapter 3 \u00b7 Samuel Comes to Bethlehem",
    narration: "Eliab looks like a king. Samuel's first instinct is understandable\u2014and incomplete.", displayText: "Eliab looks like a king. Samuel's first instinct is understandable\u2014and incomplete.",
    durationMs: 22000, camera: "medium", transition: "dissolve",
    background: bg("eliab-reveal-bg", "linear-gradient(135deg,#365314,#0f172a)", "Surely this is the one \u2014 cinematic illustrated scene"),
    interaction: {
      id: "eliab-reveal-interaction", mode: "choice", prompt: "What is the danger of judging only by appearance?", pauseTimeline: true, skippable: false,
      choices: [{ id: "eliab-reveal-0", label: "We may overlook inner character" }, { id: "eliab-reveal-1", label: "Appearance never matters" }, { id: "eliab-reveal-2", label: "Strong people cannot lead" }],
      hint: "Look for the deeper principle, not only the visible action.",
    },
    timeline: completeTimeline("eliab-reveal", 22000, "discovery", true),
  },
  {
    id: "heart-not-height", kind: "explanation", title: "The heart, not the height",
    eyebrow: "Chapter 3 \u00b7 Samuel Comes to Bethlehem",
    narration: "The story redirects attention from what is impressive to what is true. Leadership begins inside before it becomes visible outside.", displayText: "The story redirects attention from what is impressive to what is true. Leadership begins inside before it becomes visible outside.",
    durationMs: 18000, camera: "medium", transition: "dissolve",
    background: bg("heart-not-height-bg", "linear-gradient(135deg,#78350f,#111827)", "The heart, not the height \u2014 cinematic illustrated scene"),
    overlays: [{ id: "heart-not-height-takeaway", kind: "key-takeaway", title: "Remember", body: "People can see appearance. Character is revealed over time.", position: "bottom-right" }],
    timeline: completeTimeline("heart-not-height", 18000, "story", false),
  },
  {
    id: "call-david", kind: "story", title: "Send for him",
    eyebrow: "Chapter 4 \u00b7 The Unexpected Choice",
    narration: "The family waits while David is called from the fields. The overlooked son becomes the centre of the moment.", displayText: "The family waits while David is called from the fields. The overlooked son becomes the centre of the moment.",
    durationMs: 18000, camera: "wide", transition: "dissolve",
    background: bg("call-david-bg", "linear-gradient(135deg,#312e81,#0f172a)", "Send for him \u2014 cinematic illustrated scene"),
    timeline: completeTimeline("call-david", 18000, "story", false),
  },
  {
    id: "anointing", kind: "documentary", title: "Anointed in the middle of his brothers",
    eyebrow: "Chapter 4 \u00b7 The Unexpected Choice",
    narration: "David receives a promise, not a throne. Calling arrives long before fulfilment.", displayText: "David receives a promise, not a throne. Calling arrives long before fulfilment.",
    durationMs: 18000, camera: "wide", transition: "dissolve",
    background: bg("anointing-bg", "linear-gradient(135deg,#7c5e3c,#14213d)", "Anointed in the middle of his brothers \u2014 cinematic illustrated scene"),
    overlays: [{ id: "anointing-takeaway", kind: "key-takeaway", title: "Remember", body: "A promise may begin a journey rather than complete it.", position: "bottom-right" }],
    timeline: completeTimeline("anointing", 18000, "story", false),
  },
  {
    id: "return-fields", kind: "reflection", title: "Back to the sheep",
    eyebrow: "Chapter 4 \u00b7 The Unexpected Choice",
    narration: "After an extraordinary moment, David returns to ordinary responsibility. What would that require of him?", displayText: "After an extraordinary moment, David returns to ordinary responsibility. What would that require of him?",
    durationMs: 22000, camera: "reflection", transition: "dissolve",
    background: bg("return-fields-bg", "linear-gradient(135deg,#475569,#111827)", "Back to the sheep \u2014 cinematic illustrated scene"),
    interaction: {
      id: "return-fields-interaction", mode: "reflection", prompt: "How would you stay faithful after receiving a big promise?", pauseTimeline: true, skippable: false,
      hint: "Look for the deeper principle, not only the visible action.",
    },
    timeline: completeTimeline("return-fields", 22000, "reflection", true),
  },
  {
    id: "saul-troubled", kind: "story", title: "A troubled king",
    eyebrow: "Chapter 5 \u00b7 Music in the Palace",
    narration: "Saul's court needs someone who can bring calm. David enters the palace not as king, but as a musician and servant.", displayText: "Saul's court needs someone who can bring calm. David enters the palace not as king, but as a musician and servant.",
    durationMs: 18000, camera: "wide", transition: "dissolve",
    background: bg("saul-troubled-bg", "linear-gradient(135deg,#365314,#0f172a)", "A troubled king \u2014 cinematic illustrated scene"),
    timeline: completeTimeline("saul-troubled", 18000, "story", false),
  },
  {
    id: "harp-service", kind: "conversation", title: "Leadership through service",
    eyebrow: "Chapter 5 \u00b7 Music in the Palace",
    narration: "David's first palace role is to help another leader. He learns the room before he leads the room.", displayText: "David's first palace role is to help another leader. He learns the room before he leads the room.",
    durationMs: 22000, camera: "medium", transition: "dissolve",
    background: bg("harp-service-bg", "linear-gradient(135deg,#78350f,#111827)", "Leadership through service \u2014 cinematic illustrated scene"),
    interaction: {
      id: "harp-service-interaction", mode: "choice", prompt: "What can service teach a future leader?", pauseTimeline: true, skippable: false,
      choices: [{ id: "harp-service-0", label: "How people feel and what they need" }, { id: "harp-service-1", label: "How to demand attention" }, { id: "harp-service-2", label: "How to avoid responsibility" }],
      hint: "Look for the deeper principle, not only the visible action.",
    },
    timeline: completeTimeline("harp-service", 22000, "story", true),
  },
  {
    id: "two-worlds", kind: "comparison", title: "Palace and pasture",
    eyebrow: "Chapter 5 \u00b7 Music in the Palace",
    narration: "David moves between royal halls and open fields. One world teaches people; the other teaches solitude.", displayText: "David moves between royal halls and open fields. One world teaches people; the other teaches solitude.",
    durationMs: 18000, camera: "medium", transition: "dissolve",
    background: bg("two-worlds-bg", "linear-gradient(135deg,#312e81,#0f172a)", "Palace and pasture \u2014 cinematic illustrated scene"),
    overlays: [{ id: "two-worlds-takeaway", kind: "key-takeaway", title: "Remember", body: "Preparation often comes from more than one environment.", position: "bottom-right" }],
    timeline: completeTimeline("two-worlds", 18000, "story", false),
  },
  {
    id: "lion-appears", kind: "story", title: "When danger enters the field",
    eyebrow: "Chapter 6 \u00b7 The Lion and the Bear",
    narration: "A predator does not announce a lesson. It simply threatens what David has been trusted to protect.", displayText: "A predator does not announce a lesson. It simply threatens what David has been trusted to protect.",
    durationMs: 18000, camera: "wide", transition: "dissolve",
    background: bg("lion-appears-bg", "linear-gradient(135deg,#7c5e3c,#14213d)", "When danger enters the field \u2014 cinematic illustrated scene"),
    timeline: completeTimeline("lion-appears", 18000, "story", false),
  },
  {
    id: "protect-or-run", kind: "assessment", title: "A private decision",
    eyebrow: "Chapter 6 \u00b7 The Lion and the Bear",
    narration: "No army is watching. No song will be written today. David must decide whether responsibility is worth the risk.", displayText: "No army is watching. No song will be written today. David must decide whether responsibility is worth the risk.",
    durationMs: 22000, camera: "medium", transition: "dissolve",
    background: bg("protect-or-run-bg", "linear-gradient(135deg,#475569,#111827)", "A private decision \u2014 cinematic illustrated scene"),
    interaction: {
      id: "protect-or-run-interaction", mode: "choice", prompt: "What makes this moment important?", pauseTimeline: true, skippable: false,
      choices: [{ id: "protect-or-run-0", label: "David acts when nobody is watching" }, { id: "protect-or-run-1", label: "The lion is larger than Goliath" }, { id: "protect-or-run-2", label: "David wants public recognition" }],
      hint: "Look for the deeper principle, not only the visible action.",
    },
    timeline: completeTimeline("protect-or-run", 22000, "assessment", true),
  },
  {
    id: "bear-memory", kind: "recap", title: "Courage becomes memory",
    eyebrow: "Chapter 6 \u00b7 The Lion and the Bear",
    narration: "The lion and the bear become evidence David can remember later. Past faithfulness changes how he interprets future danger.", displayText: "The lion and the bear become evidence David can remember later. Past faithfulness changes how he interprets future danger.",
    durationMs: 18000, camera: "medium", transition: "dissolve",
    background: bg("bear-memory-bg", "linear-gradient(135deg,#365314,#0f172a)", "Courage becomes memory \u2014 cinematic illustrated scene"),
    overlays: [{ id: "bear-memory-takeaway", kind: "key-takeaway", title: "Remember", body: "Memory can turn yesterday's struggle into tomorrow's confidence.", position: "bottom-right" }],
    timeline: completeTimeline("bear-memory", 18000, "story", false),
    memoryHooks: [{ id: "bear-memory-memory", topic: "Past faithfulness becomes future confidence", importance: "high", conceptIds: ["memory", "courage"] }],
  },
  {
    id: "valley-wide", kind: "documentary", title: "Two armies, one valley",
    eyebrow: "Chapter 7 \u00b7 Fear in the Valley",
    narration: "Israel and Philistia face one another across the valley. Weapons are present. Numbers are present. Movement is absent.", displayText: "Israel and Philistia face one another across the valley. Weapons are present. Numbers are present. Movement is absent.",
    durationMs: 18000, camera: "wide", transition: "dissolve",
    background: bg("valley-wide-bg", "linear-gradient(135deg,#78350f,#111827)", "Two armies, one valley \u2014 cinematic illustrated scene"),
    timeline: completeTimeline("valley-wide", 18000, "story", false),
  },
  {
    id: "army-frozen", kind: "discovery", title: "Strength made useless",
    eyebrow: "Chapter 7 \u00b7 Fear in the Valley",
    narration: "Observe the soldiers. Fear has not removed their weapons; it has made them unable to use what they already possess.", displayText: "Observe the soldiers. Fear has not removed their weapons; it has made them unable to use what they already possess.",
    durationMs: 22000, camera: "medium", transition: "dissolve",
    background: bg("army-frozen-bg", "linear-gradient(135deg,#312e81,#0f172a)", "Strength made useless \u2014 cinematic illustrated scene"),
    interaction: {
      id: "army-frozen-interaction", mode: "discovery", prompt: "What seems to control the army?", pauseTimeline: true, skippable: false,
      choices: [{ id: "army-frozen-0", label: "Fear" }, { id: "army-frozen-1", label: "Lack of weapons" }, { id: "army-frozen-2", label: "Distance" }],
      hint: "Look for the deeper principle, not only the visible action.",
    },
    timeline: completeTimeline("army-frozen", 22000, "discovery", true),
    memoryHooks: [{ id: "army-frozen-memory", topic: "Fear can neutralise ability", importance: "high", conceptIds: ["fear", "leadership"] }],
  },
  {
    id: "david-arrives", kind: "conversation", title: "A different question",
    eyebrow: "Chapter 7 \u00b7 Fear in the Valley",
    narration: "David arrives carrying food, not armour. Yet he asks what everyone else has stopped asking: Why should this threat define us?", displayText: "David arrives carrying food, not armour. Yet he asks what everyone else has stopped asking: Why should this threat define us?",
    durationMs: 18000, camera: "medium", transition: "dissolve",
    background: bg("david-arrives-bg", "linear-gradient(135deg,#7c5e3c,#14213d)", "A different question \u2014 cinematic illustrated scene"),
    timeline: completeTimeline("david-arrives", 18000, "story", false),
  },
  {
    id: "goliath-voice", kind: "story", title: "The voice in the valley",
    eyebrow: "Chapter 8 \u00b7 The Giant Speaks",
    narration: "Goliath's greatest weapon may not be his spear. His repeated words have trained an army to expect defeat.", displayText: "Goliath's greatest weapon may not be his spear. His repeated words have trained an army to expect defeat.",
    durationMs: 18000, camera: "wide", transition: "dissolve",
    background: bg("goliath-voice-bg", "linear-gradient(135deg,#475569,#111827)", "The voice in the valley \u2014 cinematic illustrated scene"),
    overlays: [{ id: "goliath-voice-takeaway", kind: "key-takeaway", title: "Remember", body: "Repeated fear can become a story people believe.", position: "bottom-right" }],
    timeline: completeTimeline("goliath-voice", 18000, "story", false),
  },
  {
    id: "brother-rebuke", kind: "conversation", title: "Resistance from nearby",
    eyebrow: "Chapter 8 \u00b7 The Giant Speaks",
    narration: "David's oldest brother questions his motives. Sometimes courage must survive criticism before it ever faces the main challenge.", displayText: "David's oldest brother questions his motives. Sometimes courage must survive criticism before it ever faces the main challenge.",
    durationMs: 22000, camera: "medium", transition: "dissolve",
    background: bg("brother-rebuke-bg", "linear-gradient(135deg,#365314,#0f172a)", "Resistance from nearby \u2014 cinematic illustrated scene"),
    interaction: {
      id: "brother-rebuke-interaction", mode: "choice", prompt: "What should David do with unfair criticism?", pauseTimeline: true, skippable: false,
      choices: [{ id: "brother-rebuke-0", label: "Listen for truth, then stay focused" }, { id: "brother-rebuke-1", label: "Abandon the task" }, { id: "brother-rebuke-2", label: "Attack his brother" }],
      hint: "Look for the deeper principle, not only the visible action.",
    },
    timeline: completeTimeline("brother-rebuke", 22000, "story", true),
  },
  {
    id: "saul-dialogue", kind: "assessment", title: "What evidence does David have?",
    eyebrow: "Chapter 8 \u00b7 The Giant Speaks",
    narration: "David does not claim he has never felt fear. He points to what he has already survived and learned.", displayText: "David does not claim he has never felt fear. He points to what he has already survived and learned.",
    durationMs: 22000, camera: "medium", transition: "dissolve",
    background: bg("saul-dialogue-bg", "linear-gradient(135deg,#78350f,#111827)", "What evidence does David have? \u2014 cinematic illustrated scene"),
    interaction: {
      id: "saul-dialogue-interaction", mode: "text", prompt: "What past experience gives David confidence now?", pauseTimeline: true, skippable: false,
      acceptedAnswers: ["lion", "bear", "lion and bear", "protecting the sheep"], hint: "Think about the dangers David faced while caring for the flock.",
    },
    timeline: completeTimeline("saul-dialogue", 22000, "assessment", true),
  },
  {
    id: "armour-test", kind: "comparison", title: "Borrowed armour",
    eyebrow: "Chapter 9 \u00b7 Five Smooth Stones",
    narration: "Saul offers proven equipment, but it does not fit David's experience. Preparation must be real, not borrowed.", displayText: "Saul offers proven equipment, but it does not fit David's experience. Preparation must be real, not borrowed.",
    durationMs: 18000, camera: "medium", transition: "dissolve",
    background: bg("armour-test-bg", "linear-gradient(135deg,#312e81,#0f172a)", "Borrowed armour \u2014 cinematic illustrated scene"),
    timeline: completeTimeline("armour-test", 18000, "story", false),
  },
  {
    id: "stones-stream", kind: "discovery", title: "Five smooth stones",
    eyebrow: "Chapter 9 \u00b7 Five Smooth Stones",
    narration: "David chooses familiar tools with deliberate care. Simplicity is not the absence of preparation.", displayText: "David chooses familiar tools with deliberate care. Simplicity is not the absence of preparation.",
    durationMs: 22000, camera: "medium", transition: "dissolve",
    background: bg("stones-stream-bg", "linear-gradient(135deg,#7c5e3c,#14213d)", "Five smooth stones \u2014 cinematic illustrated scene"),
    interaction: {
      id: "stones-stream-interaction", mode: "discovery", prompt: "Why might David choose tools he already knows?", pauseTimeline: true, skippable: false,
      choices: [{ id: "stones-stream-0", label: "Familiar skill is more useful than impressive equipment" }, { id: "stones-stream-1", label: "He wants the battle to last longer" }, { id: "stones-stream-2", label: "Armour is always wrong" }],
      hint: "Look for the deeper principle, not only the visible action.",
    },
    timeline: completeTimeline("stones-stream", 22000, "discovery", true),
  },
  {
    id: "run-toward", kind: "story", title: "He ran toward the battle",
    eyebrow: "Chapter 9 \u00b7 Five Smooth Stones",
    narration: "David moves forward while others remain still. Courage becomes visible through action.", displayText: "David moves forward while others remain still. Courage becomes visible through action.",
    durationMs: 18000, camera: "wide", transition: "dissolve",
    background: bg("run-toward-bg", "linear-gradient(135deg,#475569,#111827)", "He ran toward the battle \u2014 cinematic illustrated scene"),
    overlays: [{ id: "run-toward-takeaway", kind: "key-takeaway", title: "Remember", body: "Courage is not only what you believe. It is the next faithful action.", position: "bottom-right" }],
    timeline: completeTimeline("run-toward", 18000, "story", false),
  },
  {
    id: "stone-flies", kind: "celebration", title: "The visible battle ends",
    eyebrow: "Chapter 10 \u00b7 Victory and Reflection",
    narration: "The stone flies. The giant falls. The moment is sudden\u2014but it rests on years of unseen preparation.", displayText: "The stone flies. The giant falls. The moment is sudden\u2014but it rests on years of unseen preparation.",
    durationMs: 18000, camera: "wide", transition: "dissolve",
    background: bg("stone-flies-bg", "linear-gradient(135deg,#365314,#0f172a)", "The visible battle ends \u2014 cinematic illustrated scene"),
    timeline: completeTimeline("stone-flies", 18000, "celebration", false),
  },
  {
    id: "before-giant", kind: "reflection", title: "Before the giant",
    eyebrow: "Chapter 10 \u00b7 Victory and Reflection",
    narration: "David did not become courageous in the valley. The valley revealed what the fields had already formed.", displayText: "David did not become courageous in the valley. The valley revealed what the fields had already formed.",
    durationMs: 22000, camera: "reflection", transition: "dissolve",
    background: bg("before-giant-bg", "linear-gradient(135deg,#78350f,#111827)", "Before the giant \u2014 cinematic illustrated scene"),
    overlays: [{ id: "before-giant-takeaway", kind: "key-takeaway", title: "Remember", body: "Great victories are prepared long before they are seen.", position: "bottom-right" }],
    interaction: {
      id: "before-giant-interaction", mode: "reflection", prompt: "Which quiet habit could prepare you for a future challenge?", pauseTimeline: true, skippable: false,
      hint: "Look for the deeper principle, not only the visible action.",
    },
    timeline: completeTimeline("before-giant", 22000, "reflection", true),
    memoryHooks: [{ id: "before-giant-memory", topic: "Courage is prepared before crisis", importance: "high", conceptIds: ["courage", "preparation", "leadership"] }],
  },
  {
    id: "final-takeaway", kind: "celebration", title: "Carry this with you",
    eyebrow: "Chapter 10 \u00b7 Victory and Reflection",
    narration: "The battle lasted moments. The preparation took years. What you practise quietly today may become strength for someone else tomorrow.", displayText: "The battle lasted moments. The preparation took years. What you practise quietly today may become strength for someone else tomorrow.",
    durationMs: 18000, camera: "wide", transition: "dissolve",
    background: bg("final-takeaway-bg", "linear-gradient(135deg,#312e81,#0f172a)", "Carry this with you \u2014 cinematic illustrated scene"),
    overlays: [{ id: "final-takeaway-takeaway", kind: "key-takeaway", title: "Remember", body: "Great victories are prepared long before they are seen.", position: "bottom-right" }],
    timeline: completeTimeline("final-takeaway", 18000, "celebration", false),
  },
];

export const davidBeforeTheGiant: StoryJourney = {
  id: "bible-david-before-the-giant", academyId: "bible", moduleId: "bible-david",
  title: "David: Before the Giant", subtitle: "The years of preparation behind one famous moment",
  summary: "A 10-chapter interactive documentary exploring how private responsibility, service and memory prepared David for the valley.",
  takeaway: "Great victories are prepared long before they are seen.", estimatedMinutes: 25,
  learningObjectives: ["Explain how David’s earlier responsibilities prepared him for Goliath", "Distinguish visible confidence from developed character", "Apply the principle of quiet preparation to a personal challenge"],
  access: { tier: "explorer", previewAllowed: true },
  characters: [
    { id: "david", displayName: "David", role: "Shepherd and future king", assetId: "character-david" },
    { id: "jesse", displayName: "Jesse", role: "David\u2019s father", assetId: "character-jesse" },
    { id: "samuel", displayName: "Samuel", role: "Prophet", assetId: "character-samuel" },
    { id: "saul", displayName: "Saul", role: "King of Israel", assetId: "character-saul" },
    { id: "eliab", displayName: "Eliab", role: "David\u2019s eldest brother", assetId: "character-eliab" },
    { id: "goliath", displayName: "Goliath", role: "Philistine champion", assetId: "character-goliath" },
  ],
  chapters: [
    { id: "house-of-jesse", order: 1, title: "The House of Jesse", summary: "Meet David before anyone considered him important.", sceneIds: ["bethlehem-morning", "brothers-line", "missing-son"] },
    { id: "life-in-fields", order: 2, title: "Life in the Fields", summary: "Discover the quiet responsibilities that trained David.", sceneIds: ["sheep-at-dusk", "notice-field", "quiet-reflection"] },
    { id: "samuel-arrives", order: 3, title: "Samuel Comes to Bethlehem", summary: "A prophet searches for the person God has chosen.", sceneIds: ["samuel-enters", "eliab-reveal", "heart-not-height"] },
    { id: "unexpected-choice", order: 4, title: "The Unexpected Choice", summary: "The overlooked shepherd is called inside.", sceneIds: ["call-david", "anointing", "return-fields"] },
    { id: "music-palace", order: 5, title: "Music in the Palace", summary: "David learns to serve before he learns to lead.", sceneIds: ["saul-troubled", "harp-service", "two-worlds"] },
    { id: "lion-bear", order: 6, title: "The Lion and the Bear", summary: "Private courage becomes preparation.", sceneIds: ["lion-appears", "protect-or-run", "bear-memory"] },
    { id: "fear-valley", order: 7, title: "Fear in the Valley", summary: "An entire army is paralysed by one voice.", sceneIds: ["valley-wide", "army-frozen", "david-arrives"] },
    { id: "giant-speaks", order: 8, title: "The Giant Speaks", summary: "David hears the same threat but interprets it differently.", sceneIds: ["goliath-voice", "brother-rebuke", "saul-dialogue"] },
    { id: "five-stones", order: 9, title: "Five Smooth Stones", summary: "Preparation, clarity and action converge.", sceneIds: ["armour-test", "stones-stream", "run-toward"] },
    { id: "victory-reflection", order: 10, title: "Victory and Reflection", summary: "The visible battle ends; the deeper lesson remains.", sceneIds: ["stone-flies", "before-giant", "final-takeaway"] },
  ], scenes,
  completion: {
    skills: ["courage", "leadership", "preparation", "reflection"], conceptIds: ["courage", "preparation", "responsibility", "leadership", "fear"],
    memorableMoment: "The battle lasted moments. The preparation took years.",
    credits: { discoveries: 6, questions: 8, reflections: 4 },
    memoryHooks: [{ id: "david-journey-complete", topic: "Courage is prepared before crisis", importance: "high", conceptIds: ["courage", "preparation", "leadership"] }],
    recommendations: [{ id: "modern-courage", trigger: "lesson_completed", reason: "You explored how courage is formed through preparation. Continue with a modern story of disciplined courage.", academyId: "biography", moduleId: "muhammad-ali", priority: 90 }],
  },
};
