import type {
  Asset,
  AssetId,
  Level,
  MarketCategory,
  NewsItem,
} from "./types";

export const STARTING_CASH = 100_000;

export const assets: Asset[] = [
  {
    id: "cash",
    name: "Cash Reserve",
    ticker: "CASH",
    category: "cash",
    description: "Immediately available FountainCash. Stable in nominal terms, but inflation can reduce purchasing power.",
    price: 1,
    volatility: 0,
    drift: 0,
    risk: 1,
    incomeLabel: "None",
    liquidity: "high",
    tags: ["liquidity", "emergency"],
  },

  {
    id: "tbill-3m",
    name: "3-Month Treasury Bill",
    ticker: "TBL3",
    category: "government",
    description: "Short-duration fictional government debt designed for high liquidity and comparatively low price volatility.",
    price: 100,
    volatility: 0.004,
    drift: 0.002,
    risk: 1,
    incomeLabel: "Short-term government yield",
    liquidity: "high",
    tags: ["defensive", "short-term"],
  },
  {
    id: "tbill-12m",
    name: "12-Month Treasury Bill",
    ticker: "TBL12",
    category: "government",
    description: "Longer-dated fictional Treasury exposure with slightly more rate sensitivity than the 3-month bill.",
    price: 100,
    volatility: 0.008,
    drift: 0.003,
    risk: 1,
    incomeLabel: "Government yield",
    liquidity: "high",
    tags: ["defensive", "income"],
  },
  {
    id: "gov-bond",
    name: "Government Bond Fund",
    ticker: "GBND",
    category: "government",
    description: "Diversified fictional government bonds. Can rise or fall as interest-rate expectations change.",
    price: 100,
    volatility: 0.018,
    drift: 0.004,
    risk: 2,
    incomeLabel: "Coupon income",
    liquidity: "high",
    tags: ["fixed income", "duration"],
  },
  {
    id: "corp-bond",
    name: "Corporate Bond Fund",
    ticker: "CBND",
    category: "government",
    description: "A diversified fictional corporate bond portfolio offering more yield alongside additional credit risk.",
    price: 100,
    volatility: 0.026,
    drift: 0.006,
    risk: 2,
    incomeLabel: "Corporate bond income",
    liquidity: "high",
    tags: ["credit", "income"],
  },

  {
    id: "global-etf",
    name: "World Equity ETF",
    ticker: "WORLD",
    category: "funds",
    description: "Broad fictional global-equity exposure across countries and sectors.",
    price: 100,
    volatility: 0.050,
    drift: 0.010,
    risk: 3,
    incomeLabel: "Dividends + business growth",
    liquidity: "high",
    tags: ["diversified", "global"],
  },
  {
    id: "dividend-etf",
    name: "Dividend Leaders ETF",
    ticker: "DIV",
    category: "funds",
    description: "Fictional basket of mature dividend-paying companies. Income-oriented, but still exposed to equity-market risk.",
    price: 100,
    volatility: 0.042,
    drift: 0.008,
    risk: 3,
    incomeLabel: "Dividends",
    liquidity: "high",
    tags: ["income", "equity"],
  },
  {
    id: "tech-etf",
    name: "Technology ETF",
    ticker: "TECH",
    category: "funds",
    description: "Concentrated fictional technology-sector fund with higher growth potential and higher volatility.",
    price: 100,
    volatility: 0.075,
    drift: 0.013,
    risk: 4,
    incomeLabel: "Business growth",
    liquidity: "high",
    tags: ["growth", "technology"],
  },
  {
    id: "smallcap-etf",
    name: "Small Companies ETF",
    ticker: "SMALL",
    category: "funds",
    description: "Fictional fund holding smaller listed businesses. More volatile and economically sensitive than a broad-market fund.",
    price: 100,
    volatility: 0.070,
    drift: 0.012,
    risk: 4,
    incomeLabel: "Business growth",
    liquidity: "high",
    tags: ["small-cap", "growth"],
  },

  {
    id: "stock-nova",
    name: "Nova Systems",
    ticker: "NOVA",
    category: "shares",
    sector: "Technology",
    description: "Fictional software company with fast revenue growth, high expectations and elevated valuation risk.",
    price: 82,
    volatility: 0.095,
    drift: 0.016,
    risk: 5,
    incomeLabel: "Growth",
    liquidity: "high",
    tags: ["growth", "software"],
  },
  {
    id: "stock-horizon",
    name: "Horizon Bank",
    ticker: "HZB",
    category: "shares",
    sector: "Financials",
    description: "Fictional bank whose earnings are sensitive to interest rates, credit quality and economic conditions.",
    price: 54,
    volatility: 0.065,
    drift: 0.010,
    risk: 4,
    incomeLabel: "Dividends + earnings",
    liquidity: "high",
    tags: ["banking", "dividend"],
  },
  {
    id: "stock-harbor",
    name: "Harbor Consumer",
    ticker: "HARB",
    category: "shares",
    sector: "Consumer Staples",
    description: "Fictional defensive consumer-products company with steadier demand and moderate dividend income.",
    price: 68,
    volatility: 0.045,
    drift: 0.008,
    risk: 3,
    incomeLabel: "Dividends + earnings",
    liquidity: "high",
    tags: ["defensive", "consumer"],
  },
  {
    id: "stock-lumina",
    name: "Lumina Energy",
    ticker: "LUM",
    category: "shares",
    sector: "Energy",
    description: "Fictional energy producer exposed to commodity prices, operating costs and the energy cycle.",
    price: 47,
    volatility: 0.080,
    drift: 0.010,
    risk: 4,
    incomeLabel: "Dividends + commodity cycle",
    liquidity: "high",
    tags: ["energy", "cyclical"],
  },
  {
    id: "stock-forge",
    name: "Forge Industrial",
    ticker: "FORG",
    category: "shares",
    sector: "Industrials",
    description: "Fictional industrial business linked to infrastructure spending, manufacturing and the economic cycle.",
    price: 61,
    volatility: 0.060,
    drift: 0.010,
    risk: 4,
    incomeLabel: "Earnings + dividends",
    liquidity: "high",
    tags: ["industrial", "cyclical"],
  },
  {
    id: "stock-vita",
    name: "Vita Health",
    ticker: "VITA",
    category: "shares",
    sector: "Healthcare",
    description: "Fictional healthcare company with resilient demand but product-development and regulation risk.",
    price: 73,
    volatility: 0.055,
    drift: 0.010,
    risk: 3,
    incomeLabel: "Business growth",
    liquidity: "high",
    tags: ["healthcare", "defensive growth"],
  },

  {
    id: "property-income",
    name: "Income Property Fund",
    ticker: "RENT",
    category: "property",
    description: "Fictional diversified property fund focused on rental income from established buildings.",
    price: 100,
    volatility: 0.040,
    drift: 0.008,
    risk: 3,
    incomeLabel: "Rental income",
    liquidity: "medium",
    tags: ["income", "real estate"],
  },
  {
    id: "property-growth",
    name: "Growth Property Fund",
    ticker: "GROWP",
    category: "property",
    description: "Fictional property strategy targeting redevelopment and capital appreciation with higher execution risk.",
    price: 100,
    volatility: 0.060,
    drift: 0.011,
    risk: 4,
    incomeLabel: "Rent + appreciation",
    liquidity: "medium",
    tags: ["development", "growth"],
  },
  {
    id: "property-logistics",
    name: "Logistics Property Fund",
    ticker: "LOGI",
    category: "property",
    description: "Fictional warehouses and distribution centres linked to trade, e-commerce and supply chains.",
    price: 100,
    volatility: 0.050,
    drift: 0.010,
    risk: 3,
    incomeLabel: "Rental income",
    liquidity: "medium",
    tags: ["logistics", "real estate"],
  },

  {
    id: "gold",
    name: "Gold",
    ticker: "GOLD",
    category: "commodities",
    description: "Fictional gold exposure. Often treated as a diversifier, but its price can still move sharply.",
    price: 100,
    volatility: 0.045,
    drift: 0.006,
    risk: 3,
    incomeLabel: "Price movement",
    liquidity: "high",
    tags: ["diversifier", "precious metals"],
  },
  {
    id: "silver",
    name: "Silver",
    ticker: "SILV",
    category: "commodities",
    description: "Fictional silver exposure influenced by investment demand and industrial use.",
    price: 100,
    volatility: 0.070,
    drift: 0.007,
    risk: 4,
    incomeLabel: "Price movement",
    liquidity: "high",
    tags: ["precious metals", "industrial"],
  },
  {
    id: "energy",
    name: "Energy Basket",
    ticker: "ENRG",
    category: "commodities",
    description: "Fictional diversified energy-commodity basket sensitive to supply shocks and global demand.",
    price: 100,
    volatility: 0.085,
    drift: 0.007,
    risk: 4,
    incomeLabel: "Price movement",
    liquidity: "high",
    tags: ["energy", "cyclical"],
  },
  {
    id: "agriculture",
    name: "Agriculture Basket",
    ticker: "AGRI",
    category: "commodities",
    description: "Fictional agricultural commodities influenced by weather, harvests and global supply chains.",
    price: 100,
    volatility: 0.060,
    drift: 0.006,
    risk: 4,
    incomeLabel: "Price movement",
    liquidity: "medium",
    tags: ["agriculture", "inflation"],
  },

  {
    id: "digital-large",
    name: "Large Digital Assets",
    ticker: "DIGI",
    category: "digital",
    description: "Fictional basket of larger digital assets. Very volatile and highly sentiment-sensitive.",
    price: 100,
    volatility: 0.140,
    drift: 0.015,
    risk: 5,
    incomeLabel: "Price movement",
    liquidity: "high",
    tags: ["digital", "high volatility"],
  },
  {
    id: "digital-growth",
    name: "Digital Growth Basket",
    ticker: "DGRW",
    category: "digital",
    description: "Fictional basket of smaller growth-oriented digital assets with extreme uncertainty.",
    price: 100,
    volatility: 0.190,
    drift: 0.018,
    risk: 5,
    incomeLabel: "Price movement",
    liquidity: "medium",
    tags: ["digital", "speculative"],
  },
  {
    id: "digital-defi",
    name: "Decentralised Finance Basket",
    ticker: "DEFI",
    category: "digital",
    description: "Fictional DeFi basket exposed to technology risk, market sentiment and rapid price swings.",
    price: 100,
    volatility: 0.180,
    drift: 0.017,
    risk: 5,
    incomeLabel: "Price movement",
    liquidity: "medium",
    tags: ["digital", "DeFi"],
  },
];

export const byId = (id: AssetId) => {
  const asset = assets.find((candidate) => candidate.id === id);
  if (!asset) throw new Error(`Unknown investment asset: ${id}`);
  return asset;
};

export const assetsForCategory = (category: MarketCategory) =>
  assets.filter((asset) => asset.category === category);

export const levels: Level[] = [
  { id: "meet-broker", number: 1, title: "Meet Your Broker", subtitle: "Make your first investment decision", description: "Learn how markets, quotes, buying, holding and selling fit together.", turns: 5, unlockScore: 58, mode: "guided" },
  { id: "build-team", number: 2, title: "Build the Team", subtitle: "Diversify with purpose", description: "Give different assets different jobs instead of depending on one outcome.", turns: 6, unlockScore: 62, mode: "guided" },
  { id: "red-screens", number: 3, title: "Red Screens", subtitle: "Meet volatility", description: "Experience falling prices without confusing movement with permanent loss.", turns: 6, unlockScore: 64, mode: "guided" },
  { id: "inflation", number: 4, title: "The Inflation Game", subtitle: "Protect purchasing power", description: "See how rates, cash, bonds, equities and real assets respond differently to inflation.", turns: 7, unlockScore: 66, mode: "guided" },
  { id: "fomo", number: 5, title: "Everyone Is Buying It", subtitle: "Survive FOMO", description: "Separate rising prices and social excitement from a reasoned investment thesis.", turns: 7, unlockScore: 68, mode: "guided" },
  { id: "drift", number: 6, title: "Portfolio Drift", subtitle: "Rebalance thoughtfully", description: "Learn how winning and losing positions gradually change the portfolio you thought you owned.", turns: 8, unlockScore: 70, mode: "guided" },
  { id: "income", number: 7, title: "Build an Income Engine", subtitle: "Income without yield chasing", description: "Balance income, resilience, growth and concentration.", turns: 8, unlockScore: 72, mode: "guided" },
  { id: "crash", number: 8, title: "The Crash", subtitle: "Stay rational under pressure", description: "Manage a severe market decline and distinguish panic from changed fundamentals.", turns: 8, unlockScore: 74, mode: "guided" },
  { id: "manager", number: 9, title: "Portfolio Manager", subtitle: "Several risks at once", description: "Handle rates, inflation, economic growth, headlines and portfolio concentration together.", turns: 10, unlockScore: 76, mode: "guided" },
  { id: "open-market", number: 10, title: "Open Market", subtitle: "Endless mode", description: "An ongoing fictional market with rotating shocks, challenges and personal bests.", turns: 999999, unlockScore: 0, mode: "endless" },
];

export const newsPool: NewsItem[] = [
  {
    id: "rates-higher",
    headline: "Central bank signals rates may stay higher for longer",
    summary: "Short-term yields remain attractive while long-duration assets face renewed pressure.",
    categoryImpact: { government: -0.01, funds: -0.008, shares: -0.01, property: -0.018 },
    impact: { "tbill-3m": 0.003, "tbill-12m": 0.002, "gov-bond": -0.012, "property-growth": -0.02, "stock-horizon": 0.008 },
    learningPoint: "Interest-rate changes can help some assets and hurt others.",
  },
  {
    id: "inflation",
    headline: "Inflation surprises markets on the upside",
    summary: "Investors reassess purchasing power, interest rates and the durability of company earnings.",
    categoryImpact: { government: -0.008, property: -0.01, commodities: 0.018 },
    impact: { gold: 0.025, energy: 0.035, "tbill-3m": 0.004 },
    learningPoint: "Nominal returns and real purchasing-power returns are not the same thing.",
  },
  {
    id: "ai",
    headline: "AI spending boom lifts technology expectations",
    summary: "Technology-linked assets rally as investors price in stronger future growth.",
    categoryImpact: { funds: 0.012, shares: 0.008 },
    impact: { "tech-etf": 0.045, "stock-nova": 0.065 },
    learningPoint: "A compelling story can support prices, but expectations can become expensive.",
  },
  {
    id: "consumer-slowdown",
    headline: "Consumer spending slows unexpectedly",
    summary: "Markets debate whether weaker demand is temporary or the start of a broader slowdown.",
    categoryImpact: { shares: -0.012, property: -0.008 },
    impact: { "stock-harbor": -0.006, "stock-horizon": -0.018, "tbill-3m": 0.003 },
    learningPoint: "Economic news affects sectors differently.",
  },
  {
    id: "energy-shock",
    headline: "Supply disruption pushes energy prices sharply higher",
    summary: "Energy-linked assets jump while businesses exposed to fuel costs face pressure.",
    categoryImpact: { commodities: 0.02, shares: -0.004 },
    impact: { energy: 0.08, "stock-lumina": 0.06, "stock-forge": -0.018 },
    learningPoint: "A shock can create winners and losers at the same time.",
  },
  {
    id: "crypto",
    headline: "Digital assets surge as speculative interest returns",
    summary: "High-volatility assets rally quickly and social-media excitement accelerates.",
    categoryImpact: { digital: 0.055 },
    impact: { "digital-growth": 0.08, "digital-defi": 0.07 },
    learningPoint: "Fast price rises can intensify FOMO and concentration risk.",
  },
  {
    id: "crash",
    headline: "Global markets fall sharply as recession fears spread",
    summary: "Risk assets decline together while defensive assets hold up better.",
    categoryImpact: { funds: -0.07, shares: -0.09, property: -0.055, digital: -0.14, commodities: -0.02, government: 0.012 },
    impact: { "tbill-3m": 0.003, "gov-bond": 0.02, gold: 0.025 },
    learningPoint: "Diversification is most visible when different assets respond differently under stress.",
  },
];