import type { Episode } from "./types";

export const episodes: Episode[] = [
  {
    id: "first-decision",
    number: 1,
    title: "Your First Decision",
    subtitle: "Start with FC100,000",
    setup: "You are about to make your first fictional investment decision. Nothing forces you to buy immediately.",
    objective: "Choose a reasoned first action and understand what you are buying before committing capital.",
    eventNewsId: "normal-open",
    availableMarkets: ["government", "funds", "shares", "property"],
    prompt: "Do you want to read the market brief, research investments, review your portfolio, ask AYO or go straight to the market?",
    completionMessage: "You have completed your first investment episode. Now the market will move and the next situation will begin.",
  },
  {
    id: "rates",
    number: 2,
    title: "Rates Change the Game",
    subtitle: "Interest rates move",
    setup: "The central bank has changed the conversation. Short-term yields are attractive, but rate-sensitive assets are under pressure.",
    objective: "Understand how interest rates can affect cash, Treasury bills, bonds, property and shares differently.",
    eventNewsId: "rates-higher",
    availableMarkets: ["government", "funds", "shares", "property"],
    prompt: "Read the rate news, inspect your portfolio or enter the market before making your next decision.",
    completionMessage: "You have experienced an interest-rate episode. Notice which assets responded differently.",
  },
  {
    id: "fomo",
    number: 3,
    title: "Everyone Is Buying It",
    subtitle: "Technology surges",
    setup: "Technology is everywhere. Prices are rising quickly and it feels as though everyone else is making money.",
    objective: "Experience FOMO without confusing recent price momentum with a complete investment case.",
    eventNewsId: "tech-rally",
    availableMarkets: ["government", "funds", "shares", "property"],
    prompt: "Will you chase the rally, research first, diversify elsewhere or do nothing?",
    completionMessage: "You have completed the FOMO episode. Good investing is not the same as responding fastest.",
  },
  {
    id: "inflation",
    number: 4,
    title: "The Inflation Surprise",
    subtitle: "Purchasing power matters",
    setup: "Inflation comes in hotter than expected. Cash feels safe, but purchasing power is part of the story.",
    objective: "Compare nominal stability with real purchasing power and see why different assets react differently to inflation.",
    eventNewsId: "inflation",
    availableMarkets: ["government", "funds", "shares", "property", "commodities"],
    unlockAfterEpisode: ["commodities"],
    prompt: "Review the inflation news before deciding whether your portfolio still makes sense.",
    completionMessage: "You have experienced an inflation shock and unlocked the Commodities market.",
  },
  {
    id: "company-risk",
    number: 5,
    title: "One Company, One Surprise",
    subtitle: "Earnings disappoint",
    setup: "A popular software company disappoints investors. The wider market is calmer, but one share falls much harder.",
    objective: "Understand why individual-company risk is different from broad equity-market risk.",
    eventNewsId: "earnings-miss",
    availableMarkets: ["government", "funds", "shares", "property", "commodities"],
    prompt: "Does one bad company result change your whole investment plan—or only one position?",
    completionMessage: "You have experienced individual-company risk.",
  },
  {
    id: "bull-market",
    number: 6,
    title: "When Everything Feels Easy",
    subtitle: "A strong market",
    setup: "Markets have been rising. Your winners may now be much larger than when you bought them.",
    objective: "Recognise concentration created by success and separate confidence from overconfidence.",
    eventNewsId: "bull-market",
    availableMarkets: ["government", "funds", "shares", "property", "commodities"],
    prompt: "Will you add to winners, diversify, rebalance or simply hold?",
    completionMessage: "You have completed the bull-market episode. Winning can create risk too.",
  },
  {
    id: "property",
    number: 7,
    title: "A Property Opportunity",
    subtitle: "Real assets reprice",
    setup: "Financing conditions improve and property funds become more attractive to some investors.",
    objective: "Compare property income and appreciation with liquid financial assets.",
    eventNewsId: "property-window",
    availableMarkets: ["government", "funds", "shares", "property", "commodities"],
    prompt: "Is property useful for your portfolio—or are you adding it simply because it is currently performing well?",
    completionMessage: "You have compared property with your existing investments.",
  },
  {
    id: "decline",
    number: 8,
    title: "Red Screens",
    subtitle: "Markets fall",
    setup: "Prices fall sharply. The headlines are uncomfortable and some assets are suddenly worth much less.",
    objective: "Distinguish volatility, permanent loss, changed fundamentals and panic.",
    eventNewsId: "market-drop",
    availableMarkets: ["government", "funds", "shares", "property", "commodities", "digital"],
    unlockAfterEpisode: ["digital"],
    prompt: "Before you act, decide whether something fundamental changed—or whether prices simply moved.",
    completionMessage: "You have survived a sharp market decline and unlocked Digital Assets.",
  },
  {
    id: "recession",
    number: 9,
    title: "Recession Fears",
    subtitle: "The economy weakens",
    setup: "Economic data deteriorates. Investors debate defensive assets, income and the risk of further weakness.",
    objective: "See how economic slowdowns can affect sectors and asset classes differently.",
    eventNewsId: "recession",
    availableMarkets: ["government", "funds", "shares", "property", "commodities", "digital"],
    prompt: "Review what your portfolio owns before reacting to the word recession.",
    completionMessage: "You have managed a recession-fear episode.",
  },
  {
    id: "recovery",
    number: 10,
    title: "The Rebound",
    subtitle: "Markets recover quickly",
    setup: "Markets rebound faster than many people expected. Some investors who sold during the fall are still waiting to get back in.",
    objective: "Understand why market timing requires both an exit decision and a re-entry decision.",
    eventNewsId: "recovery",
    availableMarkets: ["government", "funds", "shares", "property", "commodities", "digital"],
    prompt: "Will you change your portfolio because prices recovered—or because your reasoning changed?",
    completionMessage: "You have experienced a rapid recovery and the difficulty of market timing.",
  },
  {
    id: "drift",
    number: 11,
    title: "Your Portfolio Has Changed",
    subtitle: "Rebalancing",
    setup: "After several episodes, your portfolio may no longer resemble the one you intended to build.",
    objective: "Review concentration, risk, liquidity and portfolio drift before the final challenge.",
    eventNewsId: "portfolio-drift",
    availableMarkets: ["government", "funds", "shares", "property", "commodities", "digital"],
    prompt: "What jobs are your assets doing now—and is that still the portfolio you want?",
    completionMessage: "You have completed the portfolio-drift episode.",
  },
  {
    id: "final",
    number: 12,
    title: "The Investor Test",
    subtitle: "Several signals at once",
    setup: "There is no clean answer. Bonds rally, energy jumps, technology falls and several narratives compete for your attention.",
    objective: "Make an independent investment decision using the habits developed across the campaign.",
    eventNewsId: "final-shock",
    availableMarkets: ["government", "funds", "shares", "property", "commodities", "digital"],
    prompt: "Use the news, research, portfolio and AYO if you want—but the final decision is yours.",
    completionMessage: "You completed the 12-Episode Investor Challenge.",
  },
];
